services:
  az:
    build:
      context: .
      dockerfile: azure-cil.dockerfile
    image: azure/cli
  convert:
    build:
      context: .
      dockerfile: convppt.dockerfile
    image: convert-to-pdf
